# kindly generated by appropriated Rails generator



Mailjet.configure do |config|
  config.api_key = ENV['MAILJET_API_KEY']
  config.secret_key = ENV['MAILJET_SECRET_KEY']
  config.default_from = 'elliot@rockdontstock.com'
  config.api_version = 'v3.1'
end
# This call sends a message to the given recipient with vars and custom vars.


# prenom = "spoxzzz"
# email = "thomassarafian@gmail.com"

# variable = Mailjet::Send.create(messages: [{
#   'From'=> {
#     'Email'=> "elliot@rockdontstock.com",
#     'Name'=> "Elliot de Rock Don't Stock"
#   },
#   'To'=> [
#     {
#       'Email'=> email,
#       'Name'=> prenom
#     }
#   ],
#   'TemplateID'=> 2815845,
#   'TemplateLanguage'=> true,
#   'Subject'=> "Bienvenue chez Rock Don't Stock",
#   'Variables'=> {
#     "prénom" => "Sneaker addict",
#     "age" => "20"
#   }
# }])
# p variable.attributes['Messages']

# variable = Mailjet::Send.create(messages: [{
#   'From'=> {
#     'Email'=> 'elliot@rockdontstock.com',
#     'Name'=> 'Elliot'
#   },
#   'To'=> [
#     {
#       'Email'=> 'sauzonchloe@gmail.com',
#       'Name'=> 'Thomas'
#     }
#   ],
#   'Subject'=> "Bienvenue chez Rock Don't Stock",
#   'TextPart'=> 'My first Mailjet email',
#   'HTMLPart'=> '<h3>Dear passenger 1, welcome to <a href=\'https://www.mailjet.com/\'>Mailjet</a>!</h3><br />May the delivery force be with you!',
#   'CustomID' => 'AppGettingStartedTest'
# }]
# )
# p variable.attributes['Messages']
